#!/usr/bin/env bash
#
# build.sh — bundles Sources/*.swift into GlobalShader.app.
#
# Why swiftc in a script rather than an Xcode project: this app is a handful of source
# files and one image. What it does need is four things a bare compile cannot do.
#
#   1. Make a .app bundle. TCC (Screen Recording permission) attaches the grant to a code
#      signing identity, not to a process. Running the bare binary from a terminal
#      attaches the grant to "the terminal", so it is asked again the moment you switch
#      terminals, and all of ghostty ends up holding Screen Recording permission. A
#      bundle with its own signature makes this app hold the grant under its own name.
#
#   2. Bake in the absolute paths to glslang and spirv-cross. Launched from Finder or
#      launchd, the PATH holds neither a nix profile nor /opt/homebrew/bin — what it
#      inherits is /usr/bin:/bin:/usr/sbin:/sbin and nothing more. Finding them at build
#      time and writing them into Generated.swift removes that dependency at run time.
#
#   3. Move i18n/*.json into Sources/Strings.swift. A missing translation dies here —
#      see the header of tools/gen-strings.swift.
#
#   4. Compose the app icon. Resources/icon.png is a single full-bleed square; an .icns
#      wants it masked into the system's icon shape at ten sizes, and the reasons that is
#      a compose rather than a copy are in the header of tools/make-icon.swift.
#
set -euo pipefail
cd "$(dirname "$0")"

APP="build/GlobalShader.app"
BIN="$APP/Contents/MacOS/global-shader"
BUNDLE_ID="dev.jh.global-shader"

# VERSION is the single source of the version. Info.plist, --version, and the release zip
# name all branch off it. Written by hand in three places, they are certain to diverge.
VERSION="$(tr -d '[:space:]' < VERSION)"
# CFBundleVersion is the build number. The place for CI to put its run number; 1 without it.
BUILD_NUMBER="${GS_BUILD_NUMBER:-1}"

# LSMinimumSystemVersion in Info.plist and swiftc's -target have to agree.
#
# 13.0 builds without a single warning. The one thing that fails on 12.3 (the first
# release with ScreenCaptureKit) is `cfg.capturesAudio = false` in Capture.swift — a line
# that only spells out the default, so wrapping it in #available would reach 12.3 too.
# Claiming two more releases with no machine to check them on is another matter.
#
# 13.0 has **never actually been run**, either. That it builds is what is verified, and
# docs/performance.md says so under "What has not been measured". Leaving it at 14 for no
# reason would just narrow who can use it.
MIN_MACOS=13.0

find_tool() {
    # PATH → Homebrew prefix → nix, in that order. The nix fallback stays: for a nix
    # user that is the route that actually works.
    if command -v "$1" >/dev/null 2>&1; then
        command -v "$1"
        return
    fi
    for prefix in /opt/homebrew /usr/local; do
        if [ -x "$prefix/bin/$1" ]; then
            echo "$prefix/bin/$1"
            return
        fi
    done
    command -v nix >/dev/null 2>&1 || return
    nix build --no-link --print-out-paths "nixpkgs#$2" 2>/dev/null \
        | while read -r p; do [ -x "$p/bin/$1" ] && echo "$p/bin/$1"; done | head -1
}

# An explicit path wins over the search. A packager already knows where the tools are,
# and needs one that outlives their next upgrade: the Homebrew formula passes
# /opt/homebrew/opt/glslang/bin/glslang, which stays put across versions, where the search
# would find the Cellar path of today's version and bake a path that disappears on the
# next `brew upgrade glslang`.
GLSLANG="${GS_GLSLANG:-}"
[ -z "$GLSLANG" ] && GLSLANG="$(find_tool glslang glslang || true)"
[ -z "$GLSLANG" ] && GLSLANG="$(find_tool glslangValidator glslang || true)"
SPIRV_CROSS="${GS_SPIRV_CROSS:-}"
[ -z "$SPIRV_CROSS" ] && SPIRV_CROSS="$(find_tool spirv-cross spirv-cross || true)"

if [ -z "${GLSLANG:-}" ] || [ -z "${SPIRV_CROSS:-}" ]; then
    echo "glslang / spirv-cross not found. Either route will do:" >&2
    echo "  brew install glslang spirv-cross && ./build.sh" >&2
    echo "  nix shell nixpkgs#glslang nixpkgs#spirv-cross -c ./build.sh" >&2
    echo "Or name them: GS_GLSLANG=/path/to/glslang GS_SPIRV_CROSS=/path/to/spirv-cross" >&2
    exit 1
fi
echo "version      $VERSION ($BUILD_NUMBER)"
echo "glslang      $GLSLANG"
echo "spirv-cross  $SPIRV_CROSS"

# The translation table. A missing key dies here — the details are in that file's header.
swift tools/gen-strings.swift i18n Sources/Strings.swift

cat > Sources/Generated.swift <<EOF
// Generated by build.sh. Do not edit by hand.
enum Tools {
    static let glslang = "$GLSLANG"
    static let spirvCross = "$SPIRV_CROSS"
}

enum Build {
    static let version = "$VERSION"
    static let number = "$BUILD_NUMBER"
}
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

# The icon. Cached in build/ rather than composed straight into the bundle, because the
# rm -rf above takes the bundle with it on every single build and this costs about a
# second — which is a second added to the shader edit / rebuild loop, for a file that
# changes roughly never. The two inputs are the artwork and the script that composes it;
# deleting the .icns forces it either way.
ICNS="build/AppIcon.icns"
if [ ! -f "$ICNS" ] || [ Resources/icon.png -nt "$ICNS" ] || [ tools/make-icon.swift -nt "$ICNS" ]; then
    swift tools/make-icon.swift Resources/icon.png build/AppIcon.iconset
    iconutil -c icns build/AppIcon.iconset -o "$ICNS"
    rm -rf build/AppIcon.iconset
else
    echo "icon         cached"
fi
cp "$ICNS" "$APP/Contents/Resources/AppIcon.icns"

cat > "$APP/Contents/Info.plist" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key><string>global-shader</string>
  <key>CFBundleIdentifier</key><string>$BUNDLE_ID</string>
  <key>CFBundleName</key><string>GlobalShader</string>
  <!-- Names Contents/Resources/AppIcon.icns, extension omitted — the key predates
       extensions being expected. LSUIElement below means this never reaches the Dock;
       where it does show is Finder, Spotlight, Login Items, and the list in System
       Settings → Privacy & Security → Screen Recording, which is the one place a user
       has to pick this app out by sight. -->
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>$VERSION</string>
  <key>CFBundleVersion</key><string>$BUILD_NUMBER</string>
  <key>LSMinimumSystemVersion</key><string>$MIN_MACOS</string>
  <key>NSHighResolutionCapable</key><true/>
  <!-- What makes the app appear in System Settings → General → Language & Region. The
       choice made there is written to this app's AppleLanguages and comes back through
       Locale.preferredLanguages. The files in i18n/ are the list, so build.sh fills it in. -->
  <key>CFBundleLocalizations</key>
  <array>
$(for l in i18n/*.json; do echo "    <string>$(basename "$l" .json)</string>"; done)
  </array>
  <!-- No Dock icon, no app switcher. Only the status item. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
EOF

# Which architectures to build.
#
# A development build is arm64 alone. This is where a shader edit rebuilds every few
# seconds, and there is no reason to make that take twice as long. Releases carry both,
# through tools/release.sh.
#
#   GS_ARCHS="arm64 x86_64" ./build.sh
#
# The Intel build has never actually been run. CI's x86_64 runner confirms the build and
# --check, but never a real capture — the documentation says as much. Better to ship it
# and state what was verified than to withhold something that builds.
ARCHS="${GS_ARCHS:-arm64}"

slices=()
for arch in $ARCHS; do
    out="$BIN.$arch"
    swiftc -O -wmo \
        -target "$arch-apple-macos$MIN_MACOS" \
        -framework AppKit -framework Metal -framework QuartzCore \
        -framework ScreenCaptureKit -framework CoreVideo -framework CoreMedia \
        Sources/*.swift -o "$out"
    slices+=("$out")
done

if [ "${#slices[@]}" -eq 1 ]; then
    mv "${slices[0]}" "$BIN"
else
    lipo -create "${slices[@]}" -output "$BIN"
    rm -f "${slices[@]}"
fi
echo "architectures $(lipo -archs "$BIN")"

# Signing. What makes this app hold Screen Recording permission under its own name.
#
# A certificate is used when there is one, and it falls back to an ad-hoc signature. That
# split matters because of how TCC stores the grant.
#
#   ad-hoc        the designated requirement is `cdhash H"…"`. One byte of difference in
#                 the binary no longer matches, so **every rebuild is denied.** And the
#                 entry survives, so the checkbox in System Settings stays on and macOS
#                 never asks again — it quietly stops working.
#   certificate   becomes `identifier "…" and certificate leaf H"…"`, which survives rebuilds.
#
# The details are in the header of tools/make-signing-cert.sh.
# The identity is a shared one rather than named for this app. Few people have exactly one
# hand-built .app, and a separate identity per app only multiplies what has to be
# re-approved, while what this identity does is the same for every app.
SIGN_ID="${GS_SIGN_ID:-jh local codesign}"
if security find-certificate -c "$SIGN_ID" >/dev/null 2>&1; then
    codesign --force --sign "$SIGN_ID" --timestamp=none "$APP" >/dev/null
    echo "signature    $SIGN_ID"
else
    codesign --force --sign - --timestamp=none "$APP" >/dev/null
    echo "signature    ad-hoc"
    ADHOC=1
fi

# Show what actually got baked in. A visible cdhash means the next build breaks the
# permission, and that has to be verifiable by eye.
# An ad-hoc signature prints `# designated => …` (the requirement is implicit, so it comes
# as a comment); a certificate signature prints `designated => …`. The prefixes differ, so
# both are accepted.
REQ="$(codesign -d -r- "$APP" 2>&1 | sed -n 's/^#* *designated => //p')"
[ -n "$REQ" ] && echo "requirement  $REQ"

ln -sf "GlobalShader.app/Contents/MacOS/global-shader" build/global-shader
echo
echo "→ $APP"
echo "  ./build/global-shader shaders/crt/crt.frag"

if [ -n "${ADHOC:-}" ]; then
    cat <<'GSEOF'

⚠ Ad-hoc signed, so Screen Recording permission is tied to this build alone. Rebuild and
  System Settings will show it on while capture quietly stops working. If it is not
  working now:

    tccutil reset ScreenCapture dev.jh.global-shader
    open build/GlobalShader.app        # it asks again → allow

  To remove that round trip for good, once:

    ./tools/make-signing-cert.sh

  (Launching ./build/global-shader from a terminal looks like it works, which is easy to
   misread — it is borrowing **the terminal's** Screen Recording permission, not the app's.)
GSEOF
fi
